name: Call Remote PHP Cron

on:
  schedule:
    - cron: '0 7 * * 0'  # Runs every Sunday at 07:00

  workflow_dispatch:  # Optional: manual run

jobs:
  call-cron-php:
    runs-on: ubuntu-latest
    steps:
      - name: Call test-cron.php via HTTP
        run: |
          curl -A "Mozilla/5.0" -v "https://thiruvazhipadu.com/test-cron.php" -o response.txt --fail --max-time 30

          echo "HTTP Status Code: $?"
          echo "Response from PHP script:"
          cat response.txt
