name: Call Remote PHP Cron

on:
  schedule:
    - cron: '*/2 * * * *'  # Runs every 2 minutes
  workflow_dispatch:  # Optional: manual run

jobs:
  call-cron-php:
    runs-on: ubuntu-latest
    steps:
      - name: Call test-cron.php via HTTP
        run: |
          curl -v https://thiruvazhipadu.com/test-cron.php -o response.txt --fail --max-time 30
          echo "HTTP Status Code: $?"
          echo "Response from PHP script:"
          cat response.txt
